### ISSUE TITLE
Use etag + head request to reduce number of requests

### ISSUE THREAD

**Issue by lspgn** [cloudflare/gortr#1]

**Comment by ties** [comment]
A heads up: I wrote a quick implementation of this (see [feature/etags](https://github.com/ties/gortr/tree/feature/etags) in my fork).

This is lacking tests and uses `If-Modified-Since` instead of head requests. Do you think the approach taken would be viable for a pull request?

**Comment by lspgn** [comment]
Hi @ties, apologies for my belated response.
Yes that would be great!
Cloudflare CDN should handle those headers for https://rpki.cloudflare.com/rpki.json.

I did a quick [compare](https://github.com/cloudflare/gortr/compare/master...ties:feature/etags#), just a few comments:

Let's make
https://github.com/cloudflare/gortr/blob/6f8d812e2f213ecb80de2cb00179d130c4197ebd/cmd/gortr/gortr.go#L141
part of the struct state instead of a global variable

This way,
https://github.com/cloudflare/gortr/blob/6f8d812e2f213ecb80de2cb00179d130c4197ebd/cmd/gortr/gortr.go#L158
Can have the eTag passed as a string and return if file has not been changed.

I likely need to double check the metrics but rest seems ok.

Thank you!

**Comment by ties** [comment]
Hi @lspgn, thanks for the feedback!

I took a quick shot at incorporating your feedback. I moved the map into the state and pass the current eTag into/return it from `fetchFile` (instead of creating `func (s *state) fetchFile...`). I'm not 100% behind the name of the `state.FileWasUpdated` method.

My golang is a bit rusty so I welcome all feedback.

**Comment by lspgn** [comment]
This is better :). Your go is good!
Keep in mind not every server deals with etag, so we have to keep `wasModified`. etag comparison could be done in fetchFile in that case.
I'd write the `FileWasUpdated` the following way:
```
func (s *state) FileWasUpdated(file string, newEtag string) (updated bool) {
	if newEtag != "" && newEtag != s.etags[file] {
		log.Debugf("File was updated, Etag: '%s' -> '%s'", s.etags[file], newEtag)
		s.etags[file] = newEtag
		return true
	}
	return updated
}
```

**Comment by ties** [comment]
Thanks for the feedback :). I did another iteration. I added `State` as a companion object for `fetchFile` which reduced the passing around of etags. I also handle HTTP errors differently.

We could inline `FileWasUpdated` now but I do not mind this verbosity.

**Comment by lspgn** [comment]
Hey @ties !
Sorry for the delay.
Thanks for updating. It looks great.
Just a few things before merging:
I will need a rebase so that the change is a single commit.

I also added a commit to the branch, if you want to integrate it:
https://github.com/cloudflare/gortr/commit/e740e6c962a4efc114810991755f35e7f16cc0cc
Added an error type `IdenticalEtag` and the ability to disable eTags from command line.
I'm wondering if we need `FileWasUpdated`.

**Comment by ties** [comment]
Thanks for the small improvements --- I've integrated it and squashed the commits. I agree that `FileWasUpdated` was unneeded – it was unclear and only server to prevent an empty etag from being stored in the map.

Let's move to a pull request :).

**Comment by lspgn** [comment]
Merged :) Thank you @ties !
