### ISSUE TITLE
about config

### ISSUE THREAD

**Issue by liuxyon** [cloudflare/gortr#25]
it is can use an config file eg: 1.conf ?  i think this is easy config.

If I want to use multiple data sources at the same time, how do I configure its?

Also I did not understand how to add my own prefixes list in the configuration file?

how use ssh mode for frr?  this is need via ssh login wich port for config?  Some parts of the help file do not understand.

**Comment by lspgn** [comment]
Hello,

1. I did not understand the question? There is no configuration file, everything is passed via the command line.
2. You can only use one JSON per RTR server. But you can have as many RTR servers as you want.
3. GoRTR does not have this feature. Although, it's a request I have had a few times (enabling local configured prefixes). In the meantime: I would suggest to pre-process the JSON that is provided to GoRTR.
4. I have never configured it with FRR. You will have to follow [the guide](http://docs.frrouting.org/en/latest/bgp.html#enabling-rpki). To configure GoRTR, the steps [are there](https://github.com/cloudflare/gortr#with-ssh).

**Comment by liuxyon** [comment]
1.I mean it is recommended to increase the way you use the configuration file.
2.Add multiple sources to increase reliability. If a source data has problems or cannot be obtained, using multiple sources will not cause service interruption. 
3.RIPE allows you to host management RPKI, How do it add an json file?  this is need creat new any files?

**Comment by lspgn** [comment]
That's more of a preference of mine not to have GoRTR manage configuration files. I do not really see what would require a configuration file.

If there is an issue, it will keep using the cached data. This would add more complexity in case the two data sources are different (eg: different prefixes in the second one). This is why I'd suggest to run multiple GoRTR.

You have to add your prefixes on the RIPE RPKI dashboard here: https://my.ripe.net/#/rpki

**Comment by liuxyon** [comment]
i install the gortr_0.11.4_amd64.deb, but i can't find the /etc/gortr folder .
ubuntu 19.0.4   Linux 5.2.9-050209-lowlatency x86_64

**Comment by lspgn** [comment]
The package definition is here:
https://github.com/cloudflare/gortr/blob/master/Makefile#L53-L56

The configuration file is in `/etc/default/gortr`

**Comment by liuxyon** [comment]
i mean is lost a lot of files in /etc/gortr  like Gopkg.toml  etc...
an server not creat /etc/gortr 

The configuration file is in /etc/default/gortr  only show
GORTR_ARGS=

**Comment by lspgn** [comment]
Yes, you can populate:
`GORTR_ARGS= -cache https://example.com/rpki.json -verify=false` in /etc/default/gortr
for instance

**Comment by lspgn** [comment]
@liuxyon started a branch that implements SLURM in order to do overrides and filters (#34):
https://github.com/cloudflare/gortr/tree/feature/filter

Commenting here as this was one of your concerns.
