### ISSUE TITLE
Panic: No bounds checking after reading JSON

### ISSUE THREAD

**Issue by dotwaffle** [cloudflare/gortr#36]
From: https://github.com/cloudflare/gortr/blob/0846db61601ba06e7feb587a4e7d1877671cec39/cmd/gortr/gortr.go#L215-L217

Which is of type: https://github.com/cloudflare/gortr/blob/0846db61601ba06e7feb587a4e7d1877671cec39/prefixfile/prefixfile.go#L79-L84

As far as I can tell, you're assuming that the `"asn"` field in a json file will always start `AS`. When I supply the data `"asn": "0"` to that field, `gortr` panics.

For reasons I don't yet understand, [rpki-validator-3](https://ftp.ripe.net/tools/rpki/validator3/prod/generic/rpki-validator-3-latest-dist.tar.gz) in the latest version presents the ASN without the leading `AS`.

I would strongly suggest:

1. Using `strings.TrimLeft(v.ASN, "aAsS")` to strip out the prefix, if it exists.
2. Checking the error on `strconv.ParseUint`.

Or, make a custom type with its own `MarshalJSON()`/`UnmarshalJSON(data []byte)` methods for the `"asn"` field.

**Comment by lspgn** [comment]
Good catch, will fix this asap!
