### ISSUE TITLE
TCP port provided in bind argument is not considered

### ISSUE THREAD

**Issue by Avinash825** [cloudflare/gortr#41]
Hi, I am trying to run the software using below command , but facing issue with tcp port.

/usr/bin/gortr --bind 127.0.0.1:323
FATA [0000] listen tcp :8080: bind : address already in use

What could be the issue..

**Comment by lspgn** [comment]
It provides metrics as well (you likely have another webserver listening on :8080).

Can you do add the following: `metrics.addr :8081`?

**Comment by Avinash825** [comment]
when i tried as below got the same error but this time port number was 8282

/usr/bin/gortr -metrics.addr :8081
FATA [0000] listen tcp :8282: bind : address already in use

**Comment by lspgn** [comment]
You need to specify both arguments (single dash as well).
`/usr/bin/gortr -metrics.addr :8081 -bind 127.0.0.1:323`
