### ISSUE TITLE
Empty slurm file results in non-function

### ISSUE THREAD

**Issue by job** [cloudflare/gortr#42]
It appears that feeding GoRTR an empty slurm file (as following)

```
{
  "slurmVersion": 1,
  "validationOutputFilters": {
    "prefixFilters": [],
    "bgpsecFilters": []
  },
  "locallyAddedAssertions": {
    "prefixAssertions": [],
    "bgpsecAssertions": []
  }
}
```
results in no VRPs being exported over RTR

**Comment by lspgn** [comment]
I think the issue is here:
https://github.com/cloudflare/gortr/blob/639bf50ac3f0d7260c21d39123d5adc21869bf95/prefixfile/slurm.go#L86

It should return roas instead of added
