### ISSUE TITLE
how to set the timers sent in End of Data PDU

### ISSUE THREAD

**Issue by Avinash825** [cloudflare/gortr#52]
Hi , I want to define the values of three timers shared by cache server in case of version 1 in End of Data PDU. Is there a way to do it ?

**Comment by lspgn** [comment]
It is possible when using the API/library and setting the PDU:
https://github.com/cloudflare/gortr/blob/master/lib/server.go#L863-L865
Default values are 3600, 600, 7200.

I haven't implemented it GoRTR but will take a look tomorrow.

**Comment by Avinash825** [comment]
Thanks.. could you please also add session id configuration manually ? these would be help full in testing ..

**Comment by lspgn** [comment]
Made https://github.com/cloudflare/gortr/pull/55
Are you able to try it?

**Comment by Avinash825** [comment]
Hi, no i did not get chance to do it, i will give a try and update.

**Comment by lspgn** [comment]
Merged. You can use the new flags in `v0.14.3`.
