### ISSUE TITLE
Third-party JSON formatted VRP exports > Error updating: File is expired:

### ISSUE THREAD

**Issue by n8v8R** [cloudflare/gortr#79]
* Linux to 4.14.187  armv7l GNU/Linux
* gortr latest
___

* `gortr -bind [ipv6]:8282 -cache "https://rpki-validator.ripe.net/api/export.json" -verify=false`
* `gortr -bind [ipv6]:8282 -cache "https://rpki.gin.ntt.net/api/export.json" -verify=false`

either exhibiting:

>ERRO[0004] Error updating: File is expired: 1970-01-01 00:00:00 +0000 UTC

Are the source formats wrong or just not unsupported?

**Comment by lspgn** [comment]
Hello,
You need to use the flag -checktime=false as it checks validity in a
metadata section of the file.
This is similar for the signature (-verify=false).

**Comment by n8v8R** [comment]
Oh, I see now, had thought that format is standardised...
