### ISSUE TITLE
Using GoRTR behind proxy

### ISSUE THREAD

**Issue by wbergg** [cloudflare/gortr#8]
You cannot use GoRTR behind a proxy. There are no argument to pass for a proxy. GoRTR seems to read the environment variable $https_proxy and passing data onto the proxy, but the following is observed:

[alwa01@srv-tips-1 gortr]$ ./gortr 
ERRO[0000] Get https://rpki.cloudflare.com/rpki.json: proxyconnect tcp: tls: oversized record received with length 20527 
ERRO[0000] Error updating: Get https://rpki.cloudflare.com/rpki.json: proxyconnect tcp: tls: oversized record received with length 20527 

Attached are tcpdump and logs from the squid proxy.
[cf-gortr-squid-log.txt](https://github.com/cloudflare/gortr/files/2479018/cf-gortr-squid-log.txt)
[cf-gortr-tcpdump.txt](https://github.com/cloudflare/gortr/files/2479019/cf-gortr-tcpdump.txt)

**Comment by lspgn** [comment]
Is it a transparent proxy?

The tcpdump shows this:
`15:39:57.333825 IP sproxy.comhem.com.webcache > srv-tips-1.int.comhem.com.44244: Flags [.], seq 1:1369, ack 191, win 235, options [nop,nop,TS val 1136610890 ecr 1041010364], length 1368: HTTP: HTTP/1.1 400 Bad Request`

and the squid shows it returned an error:
`1539609847.217      0 10.12.10.19 TAG_NONE/400 4511 NONE error:invalid-request - HIER_NONE/- text/html`
Do you have a pcap file to share?

Looks like a proxy issue (is the proxy replacing the certificate?): can you fetch it with [curl](https://stackoverflow.com/questions/9445489/performing-http-requests-with-curl-using-proxy)? Can you try fetching over HTTP instead?

**Comment by wbergg** [comment]
The proxy is transparent yes.

Attaching PCAPs with and without proxy. 

Note: There is only possible to use v4 via proxy.

[gortr-pcap.zip](https://github.com/cloudflare/gortr/files/2487160/gortr-pcap.zip)

**Comment by lspgn** [comment]
@wbergg I looked at the pcap, looks like GoRTR is connecting to the proxy on port 8080. Squid is expecting an unencrypted query.

Do you have the correct parameter set in the application?
`-cache https://rpki.cloudflare.com:443/rpki.json`

Can you try with:
`-cache http://rpki.cloudflare.com:8080/rpki.json`

**Comment by wbergg** [comment]
Yes we have tried both with and without the -cache. We get the same issue. HOWEVER, if I don't specify a https_proxy, gortr is able to retrieve the information over 8080.

[xxx@srv-xxx-1 gortr]$ export http_proxy="http://sproxy.xxx.com:8080"
[xxx@srv-xxx-1 gortr]$ ./gortr -cache http://rpki.cloudflare.com:8080/rpki.json
INFO[0000] New update (60915 uniques, 60915 total prefixes). 0 bytes. Updating sha256 hash  -> 010bb9ae3062fdcaffa53939c11419e6188467aff69e293c5d9162a5b712daf3 
INFO[0000] Updated added, new serial 1                  
^C
[xxx@srv-xxx-1 gortr]$ export https_proxy="https://sproxy.xxx.com:8080"
[xxx@srv-xxx-1 gortr]$ ./gortr -cache http://rpki.cloudflare.com:8080/rpki.json
ERRO[0000] Get https://rpki.cloudflare.com/rpki.json: proxyconnect tcp: tls: oversized record received with length 20527 
ERRO[0000] Error updating: Get https://rpki.cloudflare.com/rpki.json: proxyconnect tcp: tls: oversized record received with length 20527 

And curl over https still works.

**Comment by lspgn** [comment]
The golang http client will follow the redirect.

```
curl -v http://rpki.cloudflare.com:8080/rpki.json
> GET /rpki.json HTTP/1.1
> Host: rpki.cloudflare.com:8080

< HTTP/1.1 301 Moved Permanently
< Location: https://rpki.cloudflare.com/rpki.json
```

I think this is why on the proxy it cannot access `https://rpki.cloudflare.com:443/`.
Could you give me the result of a `curl https://rpki.cloudflare.com:8080/rpki.json` on machines with the proxy?

**Comment by wbergg** [comment]
With http + https proxy env variable set:

[alwa01@srv-tips-1 ~]$ curl https://rpki.cloudflare.com:8080/rpki.json
curl: (56) Received HTTP code 403 from proxy after CONNECT

**Comment by lspgn** [comment]
This does not look like a GoRTR issue.
I will try to reproduce.
Could you give me the version and configuration of your squid?

**Comment by wbergg** [comment]
Squid 3.5

**Comment by lspgn** [comment]
A bit overdue:
I was working on the proxy function (https://github.com/cloudflare/gortr/pull/23) and could not reproduce with Squid.

Go requires those two environment variables
```
export HTTP_PROXY=schema://host:port
export HTTPS_PROXY=schema://host:port
```
