### ISSUE TITLE
GoRTR segfaults if telnet is used

### ISSUE THREAD

**Issue by wbergg** [cloudflare/gortr#9]
When GoRTR is started and up and running, if you telnet to the server on port 8282 and press enter, the program segfaults.

INFO[6078] Accepted connection from 10.1.100.1:44808 (2/0) 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x62d660]

goroutine 141 [running]:
github.com/cloudflare/gortr/lib.(*Client).Start(0xc0008f82a0)
	/home/wberg/go/gortr/src/github.com/cloudflare/gortr/lib/server.go:644 +0x380
created by github.com/cloudflare/gortr/lib.(*Server).loopTCP
	/home/wberg/go/gortr/src/github.com/cloudflare/gortr/lib/server.go:488 +0x270

**Comment by lspgn** [comment]
```
pkt := buf[0:length]
dec, _ := DecodeBytes(pkt)
```

Looks like I am not handling the decoding of an empty packet.

Will fix this.

Thank you
